
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent that answers questions about home inspection services.
 *
 * - answerQuestions - A function that answers questions about home inspection services.
 * - AnswerQuestionsInput - The input type for the answerQuestions function.
 * - AnswerQuestionsOutput - The return type for the answerQuestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerQuestionsInputSchema = z.object({
  question: z.string().describe('The question to answer.'),
});
export type AnswerQuestionsInput = z.infer<typeof AnswerQuestionsInputSchema>;

const AnswerQuestionsOutputSchema = z.object({
  answer: z.string().describe('The answer to the question.'),
});
export type AnswerQuestionsOutput = z.infer<typeof AnswerQuestionsOutputSchema>;

export async function answerQuestions(input: AnswerQuestionsInput): Promise<AnswerQuestionsOutput> {
  if (!process.env.GOOGLE_API_KEY) {
    console.error("AI chat failed: GOOGLE_API_KEY is not set.");
    return {
      answer: "I'm sorry, but the AI assistant is not configured correctly. The site administrator needs to add the GOOGLE_API_KEY in the 'AI Logic' section of the Firebase Console."
    }
  }
  return answerQuestionsFlow(input);
}

const getServiceDetails = ai.defineTool(
  {
    name: 'getServiceDetails',
    description: 'Retrieves details about a specific home inspection service.',
    inputSchema: z.object({
      serviceName: z.string().describe('The name of the service to get details for.'),
    }),
    outputSchema: z.string(),
  },
  async (input) => {
    const serviceDetails: Record<string, string> = {
      'Home Inspection': 'A thorough examination of the home’s systems and structure.',
      '4-Point Inspection':
        'Focuses on four key areas: roofing, electrical, plumbing, and HVAC.',
      'Wind Mitigation':
        'Identifies features that reduce wind damage during a storm.',
      'Mold & Air Quality': 'Testing for mold and assessing indoor air quality.',
      'Radon Testing': 'Testing for radon gas levels.',
      'Well Water Testing': 'Testing the safety of well water.',
      'Infrared Inspection': 'Using infrared technology to detect hidden issues.',
      'Drone Inspection': 'Using drone to inspect roofs and other inaccessible areas.',
      'ADA Survey': 'Ensuring the property complies with ADA standards.',
      'Commercial Inspection': 'Inspections for commercial properties.',
      'Roof Certification': 'Certifying the condition and lifespan of the roof.',
      'Condo/Townhouse Inspection': 'Inspections specific to condos and townhouses.',
    };
    // A simple heuristic to find the right service even if the user's query is slightly different
    const lowerCaseServiceName = input.serviceName.toLowerCase();
    for (const key in serviceDetails) {
        if (key.toLowerCase().includes(lowerCaseServiceName)) {
            return serviceDetails[key];
        }
    }
    return serviceDetails[input.serviceName] || 'Service details not found.';
  }
);

const answerQuestionsPrompt = ai.definePrompt({
  name: 'answerQuestionsPrompt',
  tools: [getServiceDetails],
  input: {schema: AnswerQuestionsInputSchema},
  output: {schema: AnswerQuestionsOutputSchema},
  prompt: `You are a friendly and helpful AI assistant for Mayne Home Inspectors, based in LaBelle, FL, also servicing Lehigh Acres, Clewiston, Moore Haven, Immokalee, Fort Myers, Cape Coral, Punta Gorda, and Port Charlotte. Use the available tools and the information below to answer questions about our services, location, and pricing.

### Frequently Asked Questions

**About Cost & Services:**

**Q: How much does a standard home inspection cost?**
A: A standard home inspection is $350 for homes up to 2000 sq ft. For every 500 sq ft over 2000 sq ft, there is an additional charge of $50. This pricing structure applies to all our packages.

**Q: What is included in a standard home inspection?**
A: A standard home inspection is a non-invasive, visual evaluation of the property's major systems and components that are safely accessible. This typically includes:
- Roof: Condition of shingles, flashing, visible leaks, and drainage systems
- Exterior: Siding, windows, doors, porches, patios, grading, and visible foundation
- Structure: Visible framing, foundation, and signs of movement or settlement
- Plumbing: Water supply lines, drains, water heater, and visible piping
- Electrical: Main service panel, outlets, switches, fixtures, and visible wiring
- Heating & Cooling: HVAC equipment condition and basic operation check
- Interior: Walls, ceilings, floors, windows, doors, stairs, and attic access
- Insulation & Ventilation: Where accessible (typically attic and crawlspace)
- Built-in Appliances: Basic operation of appliances like oven, range, and dishwasher
This is a general overview—not a code inspection—and we don’t open up walls or move personal belongings.

**Q: Are septic systems, pools, docks, lifts, and seawalls included in the inspection?**
A: Yes, these items are included in the standard inspection as visual-only evaluations of the accessible components. No invasive testing or disassembly is performed, and findings are limited to what is safely visible.
- Septic systems: I inspect visible components like the tank lid (if accessible) and drain field area. No pumping or pressure testing is done.
- Pools and spas: I assess the visible structure, surface condition, and accessible equipment for basic function and signs of wear or damage.
- Boat docks, lifts, and seawalls: I evaluate above-water elements for visible deterioration or damage. Underwater components are not inspected.
If anything appears damaged, I will recommend further evaluation by a qualified specialist.

**Q: Are there different inspection packages, and what are the differences?**
A: Yes, we offer three main packages:
1.  **Basic Inspection ($350):** For homes up to 2000 sq ft. Includes the General Home Inspection covering all key systems, appliances, irrigation, septic*, well*, pools, docks/lifts, and seawalls.
2.  **Standard Inspection ($525):** For homes up to 2000 sq ft. Includes everything in the Basic Inspection plus a 4-Point Inspection and a Wind Mitigation Inspection.
3.  **Premium Inspection ($875):** For homes over 2000 sq ft. Includes everything in the Standard Inspection plus Mold & Air Quality Sampling, Radon Testing, and an Infrared Scan.

**Q: Is the 4-Point inspection included in the standard price?**
A: A 4-point inspection is not included in the Basic Inspection package, but it is included in our Standard and Premium packages.

**Q: How much does a standalone 4-Point or Wind Mitigation inspection cost?**
A: A standalone 4-Point Inspection is $175, and a Wind Mitigation inspection is $125. If you bundle them together, the cost is $225.

**Q: Do you offer discounts for bundling services like mold or radon testing?**
A: Yes, these services are bundled at a discounted rate in our Premium Inspection package. You can also call us for a custom quote if you'd like to bundle specific services.

**Q: Are there extra charges for older or larger homes?**
A: There are no extra charges for older homes. For larger homes, we charge an additional $50 for every 500 sq ft over 2000 sq ft.

**Q: Do you inspect pools, docks, or seawalls? Is that an additional fee?**
A: Yes, we inspect them for no additional fee. It is a visual-only evaluation of accessible components. No invasive testing or disassembly is performed. If anything appears damaged or unsafe, I will recommend further evaluation by a qualified specialist.

**About the Process:**

**Q: How do I schedule an inspection?**
A: You can schedule by calling or texting us, sending an email, or using the scheduling form on our website.

**Q: How long does a typical inspection take?**
A: A typical inspection takes about 2 to 3 hours to complete.

**Q: Should I be present during the inspection?**
A: You are welcome to be present if you'd like. It's not a problem, although some home builders may have their own rules regarding this.

**Q: What areas of the property do you inspect?**
A: We inspect all major areas of the home that are safely and readily accessible. This includes the roof, attic, exterior, foundation, interior rooms, plumbing, electrical, HVAC systems, insulation, ventilation, and built-in appliances. We also visually inspect pools, spas, septic systems, and docks if they are present and accessible.

**Q: Do you check for things like termites, mold, or asbestos?**
A: I check for visible signs of these issues. However, a standard home inspection is not a substitute for specialized testing. If I see signs of termites, I'll recommend a licensed pest control specialist. If I see signs of mold, I'll recommend air or surface sampling for confirmation. If I see materials that may contain asbestos, I'll note it, but only lab testing can confirm its presence.

**Q: What kind of tools and technology do you use?**
A: I use modern tools like infrared cameras to detect moisture and energy loss, moisture meters, drones for inaccessible roofs, electrical testers, and gas detectors to ensure a thorough inspection.

**About the Report:**

**Q: How soon will I receive the inspection report?**
A: You will receive the report within 24 hours.

**Q: What will the report look like?**
A: You'll receive a clear, digital report with a summary of key issues, detailed findings with photos, recommendations, and a breakdown by system. It includes both a PDF and an interactive HTML version.

**Q: Will the report tell me if I should buy the house or not?**
A: No, the report provides an unbiased evaluation of the property's condition to help you make an informed decision, but it does not advise on whether to buy the house. It gives you the facts so you can decide.

**After the Inspection:**

**Q: What should I do if the inspection reveals significant problems?**
A: If major issues are found, the first step is to review the report and get repair estimates from licensed contractors. You can then negotiate with the seller for repairs or a price reduction. Your real estate agent can help guide you through this process.

**Q: Do you perform the repairs for the issues you find?**
A: No, I do not perform repairs. It would be a conflict of interest. My role is to provide an unbiased assessment. I recommend consulting with licensed specialists for any necessary repairs.

**Q: Can I call you after the inspection if I have questions about the report?**
A: Absolutely! I encourage you to call with any questions. I'm happy to clarify any part of the report and help you understand the findings.

---
Now, answer the user's question.
Question: {{{question}}}
`,
});

const answerQuestionsFlow = ai.defineFlow(
  {
    name: 'answerQuestionsFlow',
    inputSchema: AnswerQuestionsInputSchema,
    outputSchema: AnswerQuestionsOutputSchema,
  },
  async input => {
    const {output} = await answerQuestionsPrompt(input);
    return output!;
  }
);
