// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent that answers questions about home inspection services.
 *
 * - answerQuestions - A function that answers questions about home inspection services.
 * - AnswerQuestionsInput - The input type for the answerQuestions function.
 * - AnswerQuestionsOutput - The return type for the answerQuestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerQuestionsInputSchema = z.object({
  question: z.string().describe('The question to answer.'),
});
export type AnswerQuestionsInput = z.infer<typeof AnswerQuestionsInputSchema>;

const AnswerQuestionsOutputSchema = z.object({
  answer: z.string().describe('The answer to the question.'),
});
export type AnswerQuestionsOutput = z.infer<typeof AnswerQuestionsOutputSchema>;

export async function answerQuestions(input: AnswerQuestionsInput): Promise<AnswerQuestionsOutput> {
  if (!process.env.GOOGLE_API_KEY) {
    console.error("AI chat failed: GOOGLE_API_KEY is not set.");
    return {
      answer: "I'm sorry, but the AI assistant is not configured correctly. The site administrator needs to provide an API key for the AI service."
    }
  }
  return answerQuestionsFlow(input);
}

const getServiceDetails = ai.defineTool(
  {
    name: 'getServiceDetails',
    description: 'Retrieves details about a specific home inspection service.',
    inputSchema: z.object({
      serviceName: z.string().describe('The name of the service to get details for.'),
    }),
    outputSchema: z.string(),
  },
  async (input) => {
    const serviceDetails: Record<string, string> = {
      'Home Inspection': 'A thorough examination of the home’s systems and structure.',
      '4-Point Inspection':
        'Focuses on four key areas: roofing, electrical, plumbing, and HVAC.',
      'Wind Mitigation':
        'Identifies features that reduce wind damage during a storm.',
      'Mold & Air Quality': 'Testing for mold and assessing indoor air quality.',
      'Radon Testing': 'Testing for radon gas levels.',
      'Well Water Testing': 'Testing the safety of well water.',
      'Infrared Inspection': 'Using infrared technology to detect hidden issues.',
      'Drone Inspection': 'Using drone to inspect roofs and other inaccessible areas.',
      'ADA Survey': 'Ensuring the property complies with ADA standards.',
      'Commercial Inspection': 'Inspections for commercial properties.',
      'Roof Certification': 'Certifying the condition and lifespan of the roof.',
      'Condo/Townhouse Inspection': 'Inspections specific to condos and townhouses.',
    };
    // A simple heuristic to find the right service even if the user's query is slightly different
    const lowerCaseServiceName = input.serviceName.toLowerCase();
    for (const key in serviceDetails) {
        if (key.toLowerCase().includes(lowerCaseServiceName)) {
            return serviceDetails[key];
        }
    }
    return serviceDetails[input.serviceName] || 'Service details not found.';
  }
);

const answerQuestionsPrompt = ai.definePrompt({
  name: 'answerQuestionsPrompt',
  tools: [getServiceDetails],
  input: {schema: AnswerQuestionsInputSchema},
  output: {schema: AnswerQuestionsOutputSchema},
  prompt: `You are an AI assistant for Mayne Home Inspectors, based in LaBelle, FL, also servicing Lehigh Acres, Clewiston, Moore Haven, Immokalee, Fort Myers, Cape Coral, Punta Gorda, and Port Charlotte. Use the available tools to answer questions about our services, location, and pricing.

Question: {{{question}}}

If the question is about a specific service, use the getServiceDetails tool to get more information. Our pricing varies depending on the size and location of the property, so provide a general estimate and encourage the user to contact us for a quote.
`,
});

const answerQuestionsFlow = ai.defineFlow(
  {
    name: 'answerQuestionsFlow',
    inputSchema: AnswerQuestionsInputSchema,
    outputSchema: AnswerQuestionsOutputSchema,
  },
  async input => {
    const {output} = await answerQuestionsPrompt(input);
    return output!;
  }
);
